"""Initial migration


Revision ID: 077dddc90fc4
Revises: 
Create Date: 2025-05-21 19:41:46.999135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077dddc90fc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('favorite_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(length=50), nullable=False),
    sa.Column('place_name', sa.String(length=120), nullable=False),
    sa.Column('place_image', sa.String(length=1000), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('drink_id', sa.String(length=50), nullable=False),
    sa.Column('drink_name', sa.String(length=120), nullable=False),
    sa.Column('drink_image', sa.String(length=255), nullable=False),
    sa.Column('drink_glass', sa.String(length=120), nullable=True),
    sa.Column('drink_category', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('favorite_places')
    op.drop_table('users')
    # ### end Alembic commands ###
