"""empty message

Revision ID: 15cc0cf15eec
Revises: 52359ea700cf
Create Date: 2025-05-18 20:27:51.279278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15cc0cf15eec'
down_revision = '52359ea700cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(length=50), nullable=False),
    sa.Column('place_name', sa.String(length=120), nullable=False),
    sa.Column('place_image', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_places')
    # ### end Alembic commands ###
