"""empty message

Revision ID: 3b0d8db44755
Revises: 15cc0cf15eec
Create Date: 2025-05-19 19:46:37.013558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0d8db44755'
down_revision = '15cc0cf15eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drink_glass', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('drink_category', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_column('drink_category')
        batch_op.drop_column('drink_glass')

    # ### end Alembic commands ###
