"""empty message

Revision ID: b4ec88ce059c
Revises: 3b0d8db44755
Create Date: 2025-05-19 23:58:38.540735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ec88ce059c'
down_revision = '3b0d8db44755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_places', schema=None) as batch_op:
        batch_op.alter_column('place_image',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_places', schema=None) as batch_op:
        batch_op.alter_column('place_image',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
