"""empty message

Revision ID: f8c2a31cd60a
Revises: b4ec88ce059c
Create Date: 2025-05-20 00:51:40.438063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c2a31cd60a'
down_revision = 'b4ec88ce059c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_places', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
